/**
 * Shared domain types.
 *
 * Kept in its own module so both the UI and the persistence layer can import
 * them without creating a circular dependency.
 */

/**
 * Single source of truth for the displayed version: injected at build time
 * from package.json (see vite.config.ts), so the About tab can never drift
 * from the shipped manifests.
 */
export const APP_VERSION: string = import.meta.env.VITE_APP_VERSION ?? "0.0.0";

/**
 * App color themes. Every id maps 1:1 to a COMPLETE [data-theme] block in
 * src/styles.css (all tokens incl. hover/row) — adding a theme means adding
 * both a CSS block and a THEME_LIST entry below.
 */
export type Theme =
  | "dark"
  | "light"
  | "slate"
  | "amoled"
  | "vibe"
  | "one-dark-pro"
  | "dracula"
  | "github-dark"
  | "github-light"
  | "tokyo-night"
  | "monokai-pro"
  | "solarized-dark"
  | "solarized-light"
  | "nord"
  | "gruvbox"
  | "catppuccin";

export type ViewKind =
  | "units"
  | "ssh-logs"
  /** The split view of open connections (terminals + SFTP). */
  | "ssh-session";

/** Which Units sub-collection the Units page shows (segmented switcher). */
export type UnitsTab = "servers" | "keys" | "scripts" | "proxies";

/**
 * A saved SSH server unit. Secrets live in SQLite AES-256-GCM encrypted
 * (vault.rs); listings from Rust carry blank password/privateKey — the UI
 * only sends plaintext when saving.
 */
export interface SshServer {
  id: string;
  name: string;
  host: string;
  port: number;
  username: string;
  /**
   * Preferred method for the UI, but BOTH sources may be configured at once
   * (Termius-style): a password AND a saved credential key — the connector
   * tries the key first, then falls back to the password. "key" (inline
   * private key paste) is legacy and no longer offered by the forms.
   */
  auth: "password" | "key" | "cred";
  /** Plaintext only when saving; "" in listings; "-" on the wire = remove stored password. */
  password: string;
  /** Legacy inline key — no longer accepted; the body lives in Credentials. */
  private_key: string;
  /** ssh_keys row id of the linked credential ("" = none). */
  key_id: string;
  /** Pinned host-key fingerprint ("SHA256:…"); "" = not seen yet. */
  host_key: string;
  /** True in listings when a password is stored (secret never crosses IPC). */
  has_password?: boolean;
  /** Detected distribution ("ubuntu", "fedora", "windows", …); "" = unknown. */
  os?: string;
  /** ssh_proxies row id to tunnel through ("" = direct connection). */
  proxy_id?: string;
}

/** A saved proxy a server can connect through (password encrypted at rest). */
export interface SshProxy {
  id: string;
  name: string;
  kind: "http" | "socks5";
  host: string;
  port: number;
  username: string;
  /** Plaintext only when saving ("" keeps the stored one, "-" clears it); blank in listings. */
  password: string;
  has_password: boolean;
}

/** A reusable private-key credential (secrets encrypted at rest). */
export interface SshKey {
  id: string;
  name: string;
  /** Plaintext only when saving; blank in listings. */
  private_key: string;
  /** Plaintext only when saving; blank in listings. */
  passphrase: string;
  /** True when a key body is stored. */
  has_key: boolean;
  /** "SHA256:…" of the stored key — for display only. */
  fingerprint: string;
  /** OpenSSH comment; "Generated By Gravitation" on app-generated keys. */
  comment?: string;
  /** Public half (authorized_keys form) — safe to show/copy. */
  public_key?: string;
}

/** Detected server OS tokens → logo files in /icons/os ("" = no logo). */
export const OS_ICONS: Record<string, string> = {
  ubuntu: "/icons/os/ubuntu.png",
  debian: "/icons/os/debian.png",
  fedora: "/icons/os/fedora.png",
  redhat: "/icons/os/redhat.png",
  arch: "/icons/os/arch.png",
  windows: "/icons/os/windows.png",
  // Logo set has no macos file yet; the token is still recognized by Rust.
  macos: "",
};

/** A saved remote command the Units page runs with one click. */
export interface SshScript {
  id: string;
  name: string;
  description: string;
  content: string;
}

/**
 * One open SSH connection page — the Connections section of the sidebar.
 * A server can have several: each terminal click opens a NEW session
 * (like Termius tabs), and every SFTP browser page is its own entry too.
 */
export interface SshConn {
  /** Unique id of this connection page. */
  id: string;
  serverId: string;
  /** terminal = PTY console page, sftp = Files page. */
  kind: "terminal" | "sftp";
  /** Live PTY session id once the shell is open (terminal only). */
  sessionId?: string;
}

/** One SFTP directory entry. */
export interface SftpEntry {
  name: string;
  path: string;
  isDir: boolean;
  size: number;
  /** Unix seconds; 0 when unknown. */
  modified: number;
}

/** One audit row of the Logs page: who connected when, and how it ended. */
export interface SshLog {
  id: string;
  /** "user" — you, via the UI; "agent" — a model through the ssh_exec tool. */
  actor: string;
  server_id: string;
  server_name: string;
  host: string;
  /** "connect" | "disconnect" | "exec" | "shell" | "sftp-upload" | "sftp-download" */
  action: string;
  ok: boolean;
  detail: string;
  /** Unix seconds. */
  created_at: number;
}

/* ---------- OAuth client notes ---------- */

/**
 * Sign-in with a Google account only works with the user's own OAuth client.
 *
 * There is no usable built-in fallback: Google refuses third-party apps that
 * authenticate with its subscription clients (Gemini CLI / Antigravity) —
 * verified live against `cloudcode-pa`, which answers SUBSCRIPTION_REQUIRED /
 * UNSUPPORTED_CLIENT for them. The client ID therefore comes from the user's
 * Cloud Console, created as a "Desktop app" in a project where the Generative
 * Language API is enabled.
 */

/** Metadata for the theme dropdown: display label, kind and preview swatches. */
export interface ThemeMeta {
  id: Theme;
  label: string;
  kind: "dark" | "light";
  /** [background, surface, accent] — rendered as dots in the picker. */
  swatch: [string, string, string];
}

export const THEME_LIST: ThemeMeta[] = [
  { id: "dark", label: "Dark", kind: "dark", swatch: ["#101010", "#1c1c1c", "#388BFD"] },
  { id: "light", label: "Light", kind: "light", swatch: ["#F8F9FA", "#FFFFFF", "#0969DA"] },
  { id: "slate", label: "Slate", kind: "dark", swatch: ["#0F172A", "#1E293B", "#0EA5E9"] },
  { id: "amoled", label: "AMOLED Black", kind: "dark", swatch: ["#000000", "#111111", "#3B82F6"] },
  { id: "one-dark-pro", label: "One Dark Pro", kind: "dark", swatch: ["#21252B", "#282C34", "#61AFEF"] },
  { id: "dracula", label: "Dracula", kind: "dark", swatch: ["#21222C", "#282A36", "#BD93F9"] },
  { id: "github-dark", label: "GitHub Dark", kind: "dark", swatch: ["#010409", "#0D1117", "#2F81F7"] },
  { id: "github-light", label: "GitHub Light", kind: "light", swatch: ["#F6F8FA", "#FFFFFF", "#0969DA"] },
  { id: "tokyo-night", label: "Tokyo Night", kind: "dark", swatch: ["#16161E", "#1A1B26", "#7AA2F7"] },
  { id: "monokai-pro", label: "Monokai Pro", kind: "dark", swatch: ["#19181A", "#2D2A2E", "#FFD866"] },
  { id: "solarized-dark", label: "Solarized Dark", kind: "dark", swatch: ["#00212B", "#002B36", "#268BD2"] },
  { id: "solarized-light", label: "Solarized Light", kind: "light", swatch: ["#EAE3CB", "#FDF6E3", "#268BD2"] },
  { id: "nord", label: "Nord", kind: "dark", swatch: ["#242933", "#2E3440", "#88C0D0"] },
  { id: "gruvbox", label: "Gruvbox Dark", kind: "dark", swatch: ["#1D2021", "#282828", "#FABD2F"] },
  { id: "catppuccin", label: "Catppuccin Mocha", kind: "dark", swatch: ["#11111B", "#1E1E2E", "#89B4FA"] },
  { id: "vibe", label: "Synthwave", kind: "dark", swatch: ["#12081F", "#221039", "#FF5AC5"] },
];

/** Every theme the app ships with — Settings → General lists these. */
export const THEMES: Theme[] = THEME_LIST.map((t) => t.id);

